### ISSUE TITLE
Suggestion: argument to specify number of returned articles

### ISSUE THREAD

**Issue by Dan-Treacher** [kotartemiy/pygooglenews#1]
Hi there

I've just started using your pygooglenews library - it works nicely :)

I was wondering whether it's possible for an extra argument to be added to the function arguments to specify the number of returned news articles? Currently it's limited to 100 - I don't know whether that's a limit imposed by google or not...

No worries if it's not feasible.

D

**Comment by kotartemiy** [comment]
It is limited by Google's RSS. 

Unfortunately, there is no way to return more than that.
