### ISSUE TITLE
error in installing pygooglenews

### ISSUE THREAD

**Issue by gjain7** [kotartemiy/pygooglenews#45]
I have tried installing the library but it is failing to install itself.  I used collab to run it and windows 11

!pip install pygooglenews --upgrade

Collecting pygooglenews
  Using cached pygooglenews-0.1.2-py3-none-any.whl (10 kB)
Requirement already satisfied: beautifulsoup4<5.0.0,>=4.9.1 in /usr/local/lib/python3.10/dist-packages (from pygooglenews) (4.11.2)
Collecting dateparser<0.8.0,>=0.7.6 (from pygooglenews)
  Using cached dateparser-0.7.6-py2.py3-none-any.whl (362 kB)
Collecting feedparser<6.0.0,>=5.2.1 (from pygooglenews)
  Using cached feedparser-5.2.1.zip (1.2 MB)
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> See above for output.
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  Preparing metadata (setup.py) ... error
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

**Comment by climate-tech** [comment]
same

**Comment by patekOnlyPrograms** [comment]
Yep i am having that issue as well using  anaconda

**Comment by BlueberryTech123** [comment]
So I have found a sort of workaround to this issue:

1. Create a new file called `pygooglenews.py`
2. Copy the code from https://github.com/kotartemiy/pygooglenews/blob/master/pygooglenews/__init__.py into the newly created file
3. Manually install the packages:
`pip install feedparser`
`pip install dateparser`
4. `import pygooglenews` like you would normally

jus gonna copy and paste this "solution"

**Comment by patekOnlyPrograms** [comment]
> So I have found a sort of workaround to this issue:
> 
> 1. Create a new file called `pygooglenews.py`
> 2. Copy the code from https://github.com/kotartemiy/pygooglenews/blob/master/pygooglenews/__init__.py into the newly created file
> 3. Manually install the packages:
>    `pip install feedparser`
>    `pip install dateparser`
> 4. `import pygooglenews` like you would normally
> 
> jus gonna copy and paste this "solution"

will verify if this works on my computer

**Comment by rohan1827** [comment]
> > So I have found a sort of workaround to this issue:
> > 
> > 1. Create a new file called `pygooglenews.py`
> > 2. Copy the code from https://github.com/kotartemiy/pygooglenews/blob/master/pygooglenews/__init__.py into the newly created file
> > 3. Manually install the packages:
> >    `pip install feedparser`
> >    `pip install dateparser`
> > 4. `import pygooglenews` like you would normally
> > 
> > jus gonna copy and paste this "solution"
> 
> will verify if this works on my computer

not working for me!

**Comment by BlueberryTech123** [comment]
> not working for me!

Could I see your file hierarchy or any error(s) you got?

**Comment by rohan1827** [comment]
@BlueberryTech123 

got it resolved, apparently feedparser is using a deprecated method 'base64.decodestring()' i had to replace the method with 'base64.decodebytes' in the package and it worked then.

**Comment by rohan1827** [comment]
> > not working for me!
> 
> Could I see your file hierarchy or any error(s) you got?

got it resolved, apparently feedparser is using a deprecated method 'base64.decodestring()' i had to replace the method with 'base64.decodebytes' in the package and it worked then.

**Comment by vedanthv** [comment]
@rohan1827 where should the method be replaced?

**Comment by flinge** [comment]
Error installing the package in Google Colab with the following output:
```
Collecting pygooglenews
  Downloading pygooglenews-0.1.2-py3-none-any.whl (10 kB)
Requirement already satisfied: beautifulsoup4<5.0.0,>=4.9.1 in /usr/local/lib/python3.10/dist-packages (from pygooglenews) (4.12.3)
Collecting dateparser<0.8.0,>=0.7.6 (from pygooglenews)
  Downloading dateparser-0.7.6-py2.py3-none-any.whl (362 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 362.0/362.0 kB 2.9 MB/s eta 0:00:00
Collecting feedparser<6.0.0,>=5.2.1 (from pygooglenews)
  Downloading feedparser-5.2.1.zip (1.2 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.2/1.2 MB 17.7 MB/s eta 0:00:00
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> See above for output.
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  Preparing metadata (setup.py) ... error
error: metadata-generation-failed
```

**Comment by py-abhinav27** [comment]
> Error installing the package in Google Colab with the following output:
> 
> ```
> Collecting pygooglenews
>   Downloading pygooglenews-0.1.2-py3-none-any.whl (10 kB)
> Requirement already satisfied: beautifulsoup4<5.0.0,>=4.9.1 in /usr/local/lib/python3.10/dist-packages (from pygooglenews) (4.12.3)
> Collecting dateparser<0.8.0,>=0.7.6 (from pygooglenews)
>   Downloading dateparser-0.7.6-py2.py3-none-any.whl (362 kB)
>      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 362.0/362.0 kB 2.9 MB/s eta 0:00:00
> Collecting feedparser<6.0.0,>=5.2.1 (from pygooglenews)
>   Downloading feedparser-5.2.1.zip (1.2 MB)
>      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.2/1.2 MB 17.7 MB/s eta 0:00:00
>   error: subprocess-exited-with-error
>   
>   × python setup.py egg_info did not run successfully.
>   │ exit code: 1
>   ╰─> See above for output.
>   
>   note: This error originates from a subprocess, and is likely not a problem with pip.
>   Preparing metadata (setup.py) ... error
> error: metadata-generation-failed
> ```

Try creating a new .py file in the files section named pygooglenews.py and install the missing packages separately It is running perfectly

**Comment by wastu01** [comment]
Is that will be fix ?

**Comment by sebDtSci** [comment]
We have pushed a new version into Pypi, so it should work now !
