### ISSUE TITLE
Only able to retrieve 100 links

### ISSUE THREAD

**Issue by MeghnaChaudhary24** [kotartemiy/pygooglenews#9]
Hi, 
I tried to download some articles using pygooglenews but it only gives me 100 links. I put the from and to dates of 2020-01-01 and 2020-07-07. Please help.

**Comment by dryjins** [comment]
same issue here.

**Comment by kotartemiy** [comment]
100 links per search are the max capacity. The only way to increase your results is to make it day-by-day. So, 100 links per day are your maximum capacity.
